server.port=8080

# Email Configuration
spring.mail.host=webmail.genuinematch.io
spring.mail.port=587
spring.mail.username=hello@iot.theja.in
spring.mail.password=Iamlegend@1
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.bcc.address=rythubadi@theja.in
mail.reply.to.address=hello@iot.theja.in

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://admin:iamlegend@db.theja.in:27017/admin
spring.data.mongodb.database=ExhibitionForm

# WhatsApp Business API Configuration
whatsapp.api.url=https://graph.facebook.com/v17.0/YOUR_PHONE_NUMBER_ID/messages
whatsapp.api.token=YOUR_ACCESS_TOKEN7626

# Exhibition Offer Configuration
exhibition.discount=5000
exhibition.warranty=2
exhibition.booth=B-103
exhibition.time=9 AM - 6 PM
